version: "3.9"

services:
  tests:
    build: .
    command: dotnet test --logger:trx -r .
    volumes:
      # bind mount a directory to share the output of the test runner
      - type: bind
        source: .
        target: /code
